# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

O resultado da operação lógica p and q and r and s and t é falso, pois p e t são falsos, e no operador “and” basta um valor falso para que toda a expressão seja falsa. Para inverter esse resultado, é possível usar o operador lógico “not”, fazendo com que a expressão passe a ser verdadeira. Outra possibilidade é utilizar o operador "or", que faria com que o resultado fosse resultado, já que bastaria apenas um desses valores serem verdadeiros para que se retorne o valor True.

In [6]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2
p & q & r & s & t

False

In [7]:
not (p & q & r & s & t)

True

In [8]:
p or q or r or s or t

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

Ao avaliar cada uma das expressões, observa-se que p, q, r, s e u resultam em valores verdadeiros, enquanto apenas t é falso. Como o operador lógico or retorna verdadeiro quando pelo menos uma das condições é verdadeira, a expressão completa p or q or r or s or t or u terá como resultado final verdadeiro, já que há vários valores verdadeiros envolvidos. Para inverter esse resultado, utiliza-se o operador not, aplicando-o à expressão completa. Dessa forma, como o resultado original é verdadeiro, a expressão not (p or q or r or s or t or u) passa a ser falsa.

In [9]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

p or q or r or s or t or u

True

In [10]:
not (p or q or r or s or t or u)

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [11]:
import pandas as pd

In [35]:
lista3 = pd.read_csv("lista3.csv", index_col="Unnamed: 0")
lista3 = lista3.round(3)
lista3

                    0      1       2      3  Media_Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
Media_Colunas   7.881  2.149   7.881  2.149         5.015

In [36]:
(lista3.iloc[1] == lista3.iloc[2]).all() or (lista3.iloc[2] == lista3.iloc[3]).all()

np.False_

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [37]:
(lista3.iloc[0] >= 10).all()

np.False_

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [38]:
((lista3.iloc[:, 2] >= 0) & (lista3.iloc[:, 2] <= 40)).all()

np.True_

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [39]:
(lista3.iloc[-1] > 10).any()

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [40]:
lista3[(lista3 > 5) & (lista3 < 7)]

                0      1   2      3  Media_Linhas
0             NaN    NaN NaN    NaN           NaN
1             NaN    NaN NaN  5.893           NaN
2             NaN    NaN NaN    NaN           NaN
3             NaN    NaN NaN    NaN           NaN
4             NaN  5.893 NaN    NaN           NaN
Media_Colunas NaN    NaN NaN    NaN         5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [41]:
lista3[(lista3 <= 5) | (lista3 > 7)]

                    0      1       2      3  Media_Linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673    NaN         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673    NaN   0.263  0.372         2.050
Media_Colunas   7.881  2.149   7.881  2.149           NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [42]:
import numpy as np

In [43]:
array1 = np.array(lista3.iloc[:, -2])
array2 = np.array(lista3.iloc[:, -1])

((array1 >= 2) & (array1 <= 5)).any()

np.True_

Ao verificar o primeiro array, observa-se que existem valores entre 2 e 5, incluindo os limites, portanto o resultado da verificação é verdadeiro.

In [44]:
print(array1)

[0.069 5.893 2.8   1.612 0.372 2.149]

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [45]:
((array1 > -1) & (array1 < 12)).all() and ((array2 > -1) & (array2 < 12)).all()

np.True_

Todos os valores dos dois arrays estão entre -1 e 12, portanto o resultado da verificação é verdadeiro.

In [46]:
print(array1)
print(array2)

[0.069 5.893 2.8   1.612 0.372 2.149]
[10.05   2.329  1.509  9.137  2.05   5.015]